### ISSUE TITLE
It doen't compile

### ISSUE THREAD

**Issue by Premier** [alexisfacques/Node-FPGrowth#1]
node-fpgrowth/dist/fpgrowth.d.ts(1,23): error TS2688: Cannot find type definition file for 'node'.
node-fpgrowth/dist/fpgrowth.d.ts(15,22): error TS2420: Class 'FPGrowth<T>' incorrectly implements interface 'IFPGrowthEvents<T>'.
  Property 'on' is missing in type 'FPGrowth<T>'.

**Comment by alexisfacques** [comment]
Can't reproduce the issue.
Module depends on Node.JS' [events](https://github.com/Gozala/events).

Have you properly run `npm install`, if cloned this repository ?

**Comment by alexisfacques** [comment]
Added **Building from source** README as well as a runnable example
